source 'https://rubygems.org'

# Common
gem 'rails',     '4.2.0'
gem 'puma',      '~> 2.11.0'
gem 'kaminari',  '~> 0.16.3'
gem 'groupdate', '~> 2.3.0'
gem 'countries'

# Postgresql w/ postgis adapter
gem 'pg'
gem 'activerecord-postgis-adapter', '~> 3.0.0.beta2'

# Authentication and authorizations
gem 'devise'
gem 'doorkeeper', '~> 2.1.0'
gem 'cancancan'

# File uploads and processing
gem 'fog', '~> 1.26.0'
gem 'carrierwave'
gem 'mini_magick'
gem 's3_relay'

# Background jobs
gem 'sidekiq'
gem 'sinatra', require: false

# Admin dependencies
gem 'responders'
gem 'simple_form'
gem 'country_select', '~> 2.1.1'

# Api
gem 'active_model_serializers'

# Ember Frontend
gem 'ember-cli-rails', '~> 0.1.10'

# JS and stylesheets
gem 'bootstrap-select-rails'
gem 'slim-rails'
gem 'js-routes'
gem 'chartkick'
gem 'swipebox'
gem 'bootstrap-sass',     '~> 3.3.3'
gem 'kaminari-bootstrap', '~> 3.0.1'
gem 'mapbox-rails', github: 'aai/mapbox-rails'
gem 'modernizr-rails'

# Asset pipeline
gem 'jquery-rails'
gem 'sass-rails',   '~> 5.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier',     '>= 1.3.0'

# Samples
gem 'exifr'
gem 'geocoder'
gem 'carmen'

# Static pages
gem 'high_voltage', '~> 2.2.1'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner', '1.3.0'
  gem 'dotenv-rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'json_spec'
end

group :test do
  gem 'shoulda-matchers', require: false
  gem 'fakeredis'
  gem 'oauth2'
end

group :development do
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'

  gem 'guard'
  gem 'guard-livereload', require: false
  gem 'guard-rspec',      require: false
  gem 'guard-bundler',    require: false
end
