source 'https://rubygems.org'

gem 'rails', '4.2.0'

# Postgresql w/ postgis adapter
gem 'pg'
gem 'activerecord-postgis-adapter', '~> 3.0.0.beta2'

# Authentication and authorizations
gem 'devise'
gem 'doorkeeper', '~> 2.1.0'

# File uploads and processing
gem 'aws-sdk', '~> 2.0.28'
gem 'fog',     '~> 1.26.0'
gem 'carrierwave'
gem 'mini_magick'

# Background jobs
gem 'sidekiq'
gem 'sinatra', require: false

# Admin dependencies
gem 'responders'
gem 'simple_form'
gem 'country_select', '~> 2.1.1'

gem 'kaminari', '~> 0.16.3'

gem 'slim-rails'
gem 'jquery-rails'
gem 'sass-rails',   '~> 5.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier',     '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner', '1.3.0'
  gem 'dotenv-rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'json_spec'
end

group :test do
  gem 'shoulda-matchers', require: false
end

