web: rails s
redis: redis-server /usr/local/etc/redis.conf
sidekiq: bundle exec sidekiq -C config/sidekiq.yml
elasticsearch: elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml